version: "3.9"
   
services:
  # db:
  #   image: postgres
  #   container_name: mothership_api_db
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  db:
    image: nouchka/sqlite3:latest
    container_name: started_app_db
    volumes:
      - ../data/db:/root/db
    environment:
      - SQLITE3_DB=development_database.sqlite3
  app:
    container_name: starter_app
    build: .
    command: ./scripts/local/start.sh
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started
